newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡


  Thank you and congrats🎉 for opening your very first issue in this project.

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖

  Thank you and congrats🎉 for opening your first pull request.

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀.
